Repository ynput/ayon-fusion, pull requests merged in 2024-10, with the labels that each got.

#18 Set loader name on "Load sequence"
  client/ayon_fusion/plugins/load/load_sequence.py
Labels: type: enhancement

#19 Creators improve descriptions
  client/ayon_fusion/plugins/create/create_image_saver.py
  client/ayon_fusion/plugins/create/create_saver.py
Labels: type: maintenance

#23 Define app host name
  package.py
Labels: type: maintenance

#17 Trigger prelaunch hooks on farm that define the profile to run (AY-6902)
  client/ayon_fusion/hooks/pre_fusion_profile_hook.py
  client/ayon_fusion/hooks/pre_fusion_setup.py
Labels: type: bug, sponsored

#9 Use task level attributes for workfile settings
  client/ayon_fusion/api/lib.py
  client/ayon_fusion/plugins/create/create_saver.py
  client/ayon_fusion/plugins/publish/collect_instances.py
  client/ayon_fusion/plugins/publish/validate_saver_resolution.py
  server/settings.py
Labels: type: enhancement

#24 Refactor "current_task" to "current_context" for attribute value
  client/ayon_fusion/plugins/create/create_saver.py
  client/ayon_fusion/plugins/publish/collect_instances.py
  server/settings.py
Labels: type: enhancement

#21 Show/hide custom frame range attributes based on Frame Range source value
  client/ayon_fusion/plugins/create/create_saver.py
  package.py
Labels: type: enhancement, community, bump minor
